// OGAS DSEZ — 30 Seed Sellers (Dual API Fallback)
const fs = require('fs');
if (!fs.existsSync('./serviceAccountKey.json')) {
  console.error('❌ serviceAccountKey.json not found. Run: cp /Users/mac/Downloads/ogasapp-5a003-firebase-adminsdk-fbsvc-6eaae7d09f.json ./serviceAccountKey.json');
  process.exit(1);
}

let db, FieldValue;
try {
  const { initializeApp, cert } = require('firebase-admin/app');
  const { getFirestore, FieldValue: FV } = require('firebase-admin/firestore');
  initializeApp({ credential: cert(require('./serviceAccountKey.json')) });
  db = getFirestore(); FieldValue = FV;
  console.log('✅ Firebase connected (modern API)');
} catch (e) {
  const admin = require('firebase-admin');
  admin.initializeApp({ credential: admin.credential.cert(require('./serviceAccountKey.json')) });
  db = admin.firestore(); FieldValue = admin.firestore.FieldValue;
  console.log('✅ Firebase connected (legacy API)');
}

const sellers = [
  // === NDOKWA WEST ===
  { sellerId:"seed_dsez_001",businessName:"Victor Gas Ventures",ownerName:"Victor Okafor",phone:"08031234501",email:"victor.okafor@ogas.local",city:"Ndokwa West",state:"Delta State",area:"Kwale",address:"15 Market Road, Kwale",geolocation:{latitude:5.700000,longitude:6.450000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1650,stock:15,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3200,stock:12,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6500,stock:8,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Victor+Okafor&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas1/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_002",businessName:"Okechukwu Gas & Cylinders",ownerName:"Okechukwu Eze",phone:"08031234502",email:"okechukwu.eze@ogas.local",city:"Ndokwa West",state:"Delta State",area:"Utagba-Uno",address:"42 Station Road, Utagba-Uno",geolocation:{latitude:5.710000,longitude:6.460000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3300,stock:10,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6600,stock:6,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12500,stock:4,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:7,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Okechukwu+Eze&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas2/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_003",businessName:"James Gas Depot",ownerName:"James Adeyemi",phone:"08031234503",email:"james.adeyemi@ogas.local",city:"Ndokwa West",state:"Delta State",area:"Kwale",address:"8 Hospital Road, Kwale",geolocation:{latitude:5.720000,longitude:6.440000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1600,stock:20,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6400,stock:10,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:4,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=James+Adeyemi&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas3/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === NDOKWA EAST ===
  { sellerId:"seed_dsez_004",businessName:"Joseph Gas World",ownerName:"Joseph Obi",phone:"08031234504",email:"joseph.obi@ogas.local",city:"Ndokwa East",state:"Delta State",area:"Aboh",address:"23 School Street, Aboh",geolocation:{latitude:5.550000,longitude:6.520000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1700,stock:18,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3400,stock:14,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6800,stock:9,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:13000,stock:5,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:6,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Joseph+Obi&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas4/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_005",businessName:"Godwin Gas & Cylinders",ownerName:"Godwin Nwosu",phone:"08031234505",email:"godwin.nwosu@ogas.local",city:"Ndokwa East",state:"Delta State",area:"Akarai",address:"17 Church Street, Akarai",geolocation:{latitude:5.560000,longitude:6.530000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3350,stock:11,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6700,stock:7,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Godwin+Nwosu&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas5/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_006",businessName:"Helen Cylinder Depot",ownerName:"Helen Onyekachi",phone:"08031234506",email:"helen.onyekachi@ogas.local",city:"Ndokwa East",state:"Delta State",area:"Aboh",address:"55 Mosque Road, Aboh",geolocation:{latitude:5.540000,longitude:6.510000},products:[{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6900,stock:15,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:13200,stock:8,unit:"per refill"},{productId:"refill-50kg",name:"50kg Gas Refill",price:25000,stock:3,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:8,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Helen+Onyekachi&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas6/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === UGHELLI SOUTH ===
  { sellerId:"seed_dsez_007",businessName:"Kingsley Gas Mart",ownerName:"Kingsley Ibe",phone:"08031234507",email:"kingsley.ibe@ogas.local",city:"Ughelli South",state:"Delta State",area:"Otu-Jeremi",address:"10 Ogorode Road, Otu-Jeremi",geolocation:{latitude:5.350000,longitude:5.850000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1550,stock:22,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3100,stock:16,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6300,stock:11,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Kingsley+Ibe&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas7/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_008",businessName:"Mary Gas & Cylinders",ownerName:"Mary Udo",phone:"08031234508",email:"mary.udo@ogas.local",city:"Ughelli South",state:"Delta State",area:"Olomu",address:"33 Ejumehere Street, Olomu",geolocation:{latitude:5.360000,longitude:5.860000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3150,stock:13,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6400,stock:9,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12800,stock:5,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:6,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Mary+Udo&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas8/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_009",businessName:"Rose Cooking Gas",ownerName:"Rose Oghene",phone:"08031234509",email:"rose.oghene@ogas.local",city:"Ughelli South",state:"Delta State",area:"Otu-Jeremi",address:"7 DSS Road, Otu-Jeremi",geolocation:{latitude:5.340000,longitude:5.840000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1580,stock:25,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6450,stock:12,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:4,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Rose+Oghene&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas9/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === UGHELLI NORTH ===
  { sellerId:"seed_dsez_010",businessName:"Grace Cylinder Depot",ownerName:"Grace Okonkwo",phone:"08031234510",email:"grace.okonkwo@ogas.local",city:"Ughelli North",state:"Delta State",area:"Ughelli Town",address:"19 Express Way, Ughelli Town",geolocation:{latitude:5.500000,longitude:5.980000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1600,stock:20,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3200,stock:15,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6500,stock:10,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12600,stock:6,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:7,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Grace+Okonkwo&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas10/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_011",businessName:"Victor Gas Link",ownerName:"Victor Ajayi",phone:"08031234511",email:"victor.ajayi@ogas.local",city:"Ughelli North",state:"Delta State",area:"Ewreni",address:"44 New Road, Ewreni",geolocation:{latitude:5.510000,longitude:5.990000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3250,stock:12,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6550,stock:8,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Victor+Ajayi&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas11/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_012",businessName:"Michael Gas & Cylinders",ownerName:"Michael Balogun",phone:"08031234512",email:"michael.balogun@ogas.local",city:"Ughelli North",state:"Delta State",area:"Agbarha",address:"12 Old Road, Agbarha",geolocation:{latitude:5.490000,longitude:5.970000},products:[{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6600,stock:14,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12900,stock:7,unit:"per refill"},{productId:"refill-50kg",name:"50kg Gas Refill",price:24800,stock:3,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:6,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Michael+Balogun&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas12/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === WARRI SOUTH ===
  { sellerId:"seed_dsez_013",businessName:"Ngozi Energy Plus",ownerName:"Ngozi Ovie",phone:"08031234513",email:"ngozi.ovie@ogas.local",city:"Warri South",state:"Delta State",area:"Warri Town",address:"25 Market Road, Warri Town",geolocation:{latitude:5.520000,longitude:5.750000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1680,stock:30,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3350,stock:20,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6700,stock:15,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:8,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Ngozi+Ovie&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas13/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_014",businessName:"Ruth Gas Point",ownerName:"Ruth Akpor",phone:"08031234514",email:"ruth.akpor@ogas.local",city:"Warri South",state:"Delta State",area:"Effurun Market",address:"67 Station Road, Effurun Market",geolocation:{latitude:5.530000,longitude:5.760000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3400,stock:18,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6800,stock:12,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:13100,stock:7,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:7,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Ruth+Akpor&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas14/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_015",businessName:"Blessing Gas Palace",ownerName:"Blessing Omo",phone:"08031234515",email:"blessing.omo@ogas.local",city:"Warri South",state:"Delta State",area:"Okere",address:"91 Hospital Road, Okere",geolocation:{latitude:5.510000,longitude:5.740000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1650,stock:22,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6650,stock:10,unit:"per refill"},{productId:"refill-50kg",name:"50kg Gas Refill",price:25500,stock:4,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Blessing+Omo&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas15/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === UVWIE ===
  { sellerId:"seed_dsez_016",businessName:"Michael Gas Mart",ownerName:"Michael Isreal",phone:"08031234516",email:"michael.isreal@ogas.local",city:"Uvwie",state:"Delta State",area:"Effurun",address:"14 School Street, Effurun",geolocation:{latitude:5.550000,longitude:5.780000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1620,stock:25,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3250,stock:18,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6550,stock:12,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12700,stock:7,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:6,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Michael+Isreal&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas16/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_017",businessName:"Faith Gas Link",ownerName:"Faith Oteri",phone:"08031234517",email:"faith.oteri@ogas.local",city:"Uvwie",state:"Delta State",area:"Enerhen",address:"38 Church Street, Enerhen",geolocation:{latitude:5.560000,longitude:5.790000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3300,stock:14,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6600,stock:9,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Faith+Oteri&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas17/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_018",businessName:"Samuel Cylinder Depot",ownerName:"Samuel Ughelli",phone:"08031234518",email:"samuel.ughelli@ogas.local",city:"Uvwie",state:"Delta State",area:"Ugbomro",address:"52 Mosque Road, Ugbomro",geolocation:{latitude:5.540000,longitude:5.770000},products:[{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6700,stock:16,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:13200,stock:8,unit:"per refill"},{productId:"refill-50kg",name:"50kg Gas Refill",price:25200,stock:4,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:7,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Samuel+Ughelli&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas18/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === SAPELE ===
  { sellerId:"seed_dsez_019",businessName:"Patience Gas Link",ownerName:"Patience Edoja",phone:"08031234519",email:"patience.edoja@ogas.local",city:"Sapele",state:"Delta State",area:"Sapele Town",address:"29 Express Way, Sapele Town",geolocation:{latitude:5.890000,longitude:5.680000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1600,stock:20,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3200,stock:15,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6400,stock:10,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:6,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Patience+Edoja&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas19/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_020",businessName:"Godwin Gas Ventures",ownerName:"Godwin Erhiawor",phone:"08031234520",email:"godwin.erhiawor@ogas.local",city:"Sapele",state:"Delta State",area:"Amukpe",address:"76 New Road, Amukpe",geolocation:{latitude:5.900000,longitude:5.690000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3150,stock:13,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6350,stock:9,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12500,stock:5,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Godwin+Erhiawor&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas20/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_021",businessName:"Okechukwu LPG Depot",ownerName:"Okechukwu Onos",phone:"08031234521",email:"okechukwu.onos@ogas.local",city:"Sapele",state:"Delta State",area:"Sapele Town",address:"11 Old Road, Sapele Town",geolocation:{latitude:5.880000,longitude:5.670000},products:[{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6500,stock:18,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12800,stock:9,unit:"per refill"},{productId:"refill-50kg",name:"50kg Gas Refill",price:24500,stock:4,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:7,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Okechukwu+Onos&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas21/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === ETHIOPE WEST ===
  { sellerId:"seed_dsez_022",businessName:"Kingsley Gas World",ownerName:"Kingsley Onwuka",phone:"08031234522",email:"kingsley.onwuka@ogas.local",city:"Ethiope West",state:"Delta State",area:"Oghara",address:"64 Market Road, Oghara",geolocation:{latitude:5.930000,longitude:5.720000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1580,stock:18,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3180,stock:14,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6450,stock:10,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Kingsley+Onwuka&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas22/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_023",businessName:"Grace Gas Link",ownerName:"Grace Ogbolu",phone:"08031234523",email:"grace.ogbolu@ogas.local",city:"Ethiope West",state:"Delta State",area:"Mosogar",address:"18 Station Road, Mosogar",geolocation:{latitude:5.940000,longitude:5.730000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3220,stock:12,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6480,stock:8,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12600,stock:5,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:6,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Grace+Ogbolu&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas23/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_024",businessName:"Michael Gas Express",ownerName:"Michael Kwale",phone:"08031234524",email:"michael.kwale@ogas.local",city:"Ethiope West",state:"Delta State",area:"Jesse",address:"47 Hospital Road, Jesse",geolocation:{latitude:5.920000,longitude:5.710000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1550,stock:20,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6300,stock:11,unit:"per refill"},{productId:"refill-50kg",name:"50kg Gas Refill",price:24000,stock:3,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:4,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Michael+Kwale&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas24/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === ISOKO SOUTH ===
  { sellerId:"seed_dsez_025",businessName:"Blessing Gas Ventures",ownerName:"Blessing Okafor",phone:"08031234525",email:"blessing.okafor@ogas.local",city:"Isoko South",state:"Delta State",area:"Oleh",address:"33 School Street, Oleh",geolocation:{latitude:5.450000,longitude:6.350000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1650,stock:22,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3300,stock:16,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6600,stock:11,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12900,stock:6,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:6,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Blessing+Okafor&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas25/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_026",businessName:"Friday Gas Ventures",ownerName:"Friday Eze",phone:"08031234526",email:"friday.eze@ogas.local",city:"Isoko South",state:"Delta State",area:"Olomoro",address:"88 Church Street, Olomoro",geolocation:{latitude:5.460000,longitude:6.360000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3350,stock:13,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6700,stock:9,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Friday+Eze&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas26/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_027",businessName:"Joseph Energy Plus",ownerName:"Joseph Adeyemi",phone:"08031234527",email:"joseph.adeyemi@ogas.local",city:"Isoko South",state:"Delta State",area:"Oleh",address:"5 Mosque Road, Oleh",geolocation:{latitude:5.440000,longitude:6.340000},products:[{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6800,stock:15,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:13300,stock:8,unit:"per refill"},{productId:"refill-50kg",name:"50kg Gas Refill",price:25800,stock:4,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:7,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Joseph+Adeyemi&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas27/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},

  // === ANIOCHA SOUTH ===
  { sellerId:"seed_dsez_028",businessName:"Mary Gas World",ownerName:"Mary Obi",phone:"08031234528",email:"mary.obi@ogas.local",city:"Aniocha South",state:"Delta State",area:"Ogwashi-Uku",address:"22 Express Way, Ogwashi-Uku",geolocation:{latitude:6.180000,longitude:6.520000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1620,stock:20,unit:"per refill"},{productId:"refill-6kg",name:"6kg Gas Refill",price:3250,stock:15,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6500,stock:10,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:6,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Mary+Obi&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas28/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_029",businessName:"Joy Gas Palace",ownerName:"Joy Nwosu",phone:"08031234529",email:"joy.nwosu@ogas.local",city:"Aniocha South",state:"Delta State",area:"Ubulu-Uku",address:"71 New Road, Ubulu-Uku",geolocation:{latitude:6.190000,longitude:6.530000},products:[{productId:"refill-6kg",name:"6kg Gas Refill",price:3280,stock:14,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6580,stock:9,unit:"per refill"},{productId:"refill-25kg",name:"25kg Gas Refill",price:12700,stock:5,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:5,supportsPickup:true,supportsDelivery:true,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Joy+Nwosu&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas29/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()},
  { sellerId:"seed_dsez_030",businessName:"Helen LPG Depot",ownerName:"Helen Onyekachi",phone:"08031234530",email:"helen.onyekachi2@ogas.local",city:"Aniocha South",state:"Delta State",area:"Ogwashi-Uku",address:"14 Old Road, Ogwashi-Uku",geolocation:{latitude:6.170000,longitude:6.510000},products:[{productId:"refill-3kg",name:"3kg Gas Refill",price:1600,stock:18,unit:"per refill"},{productId:"refill-12.5kg",name:"12.5kg Gas Refill",price:6450,stock:11,unit:"per refill"},{productId:"refill-50kg",name:"50kg Gas Refill",price:24800,stock:4,unit:"per refill"}],rating:0,totalOrders:0,isActive:true,isVerified:true,deliveryRadiusKm:4,supportsPickup:true,supportsDelivery:false,sellerStatus:"pre-registered",statusBadge:"Coming Soon",profilePhoto:"https://ui-avatars.com/api/?name=Helen+Onyekachi&background=0d4a3a&color=fff&size=128",shopPhoto:"https://picsum.photos/seed/ogas30/400/300",isSeedData:true,createdAt:FieldValue.serverTimestamp()}
];

async function seed() {
  console.log("🚀 OGAS DSEZ: Seeding 30 sellers...");
  const batch = db.batch();
  for (const seller of sellers) {
    batch.set(db.collection('sellers').doc(seller.sellerId), seller);
    for (const product of seller.products) {
      batch.set(db.collection('products').doc(`${seller.sellerId}_${product.productId}`), {
        ...product,
        sellerId: seller.sellerId,
        businessName: seller.businessName,
        city: seller.city,
        area: seller.area,
        geolocation: seller.geolocation,
        isActive: true,
        createdAt: FieldValue.serverTimestamp()
      });
    }
  }
  await batch.commit();
  console.log(`✅ ${sellers.length} sellers seeded successfully!\n`);
  const counts = {};
  for (const s of sellers) counts[s.city] = (counts[s.city]||0)+1;
  for (const [lga,n] of Object.entries(counts).sort()) console.log(`   📍 ${lga}: ${n} sellers`);
  console.log("\n⚠️  sellerStatus: 'pre-registered' — shows 'Coming Soon' badges");
  console.log("   Buyers can browse but CANNOT place orders until activated.");
  process.exit(0);
}
seed().catch(err => { console.error("❌ Error:", err.message); process.exit(1); });
